name: Deploy to Amazon ECS Fargate

on:
  # TODO: on push 以外に良さげなタイミングないかな
  push:
    branches:
      - main

env:
  # login to aws
  AWS_REGION: ap-northeast-1
  AWS_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActions
  # push image to ecr
  ECR_REPOSITORY: mcbe/server
  # render task difinition
  ECS_TASK_DIFINITION: task-definition.json
  ECS_CONTAINER: mcbe
  # deploy
  ECS_SERVICE: mc-server
  ECS_CLUSTER: mc-chiwanano

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          # IAMロールでログイン
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          # IAMユーザでログイン
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: "false"

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
          IMAGE_NAME: "${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
        run: |
          docker build -t $IMAGE_NAME . --build-arg MCBE_SERVER_ZIP_PATH=${{ env.MCBE_SERVER_ZIP_PATH }}
          docker push $IMAGE_NAME
          echo "image=$IMAGE_NAME" >> $GITHUB_OUTPUT

      # MEMO: 以下は、一旦ECRへのプッシュまでを確認するためコメントアウト
      # - name: Fill in the new image ID in the Amazon ECS task definition
      #   id: task-def
      #   uses: aws-actions/amazon-ecs-render-task-definition@v1
      #   with:
      #     task-definition: ${{ env.ECS_TASK_DIFINITION }}
      #     container-name: ${{ env.ECS_CONTAINER }}
      #     image: ${{ steps.build-image.outputs.image }}

      # - name: Deploy Amazon ECS task definition
      #   uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      #   with:
      #     task-definition: ${{ steps.task-def.outputs.task-definition }}
      #     service: ${{ env.ECS_SERVICE }}
      #     cluster: ${{ env.ECS_CLUSTER }}
      #     wait-for-service-stability: true

      # - name: get world data
      # branch tpywao/mc-chiwanano

      # - name: get server config
      # RUN curl -LO https://gist.githubusercontent.com/tpywao/7620bdfdf478996372bb26a43c43b6cf/raw/795789431cee5513004e627763e678e106b41b0b/server.properties
